$ANSIBLE_VAULT;1.1;AES256
31383037626434373832636463663630616136326339653061306132313039303538653665366563
3736373235386334343033366163643731613561623361340a376333346130363036363765383531
65323132633231393736393638313833646466353131386233336638616239653533383235313262
6132356166316239330a363139353438613965323630386630323131383431646131303636653564
38653633383530656163353038353563653036653835646534393036376565303265353032363237
37396639306665646234306236613764386663353236646339353837393034336537356263336431
61376433666435306461393731386338313737333837383533393733366164393737363338323161
37343338613862643235
